# Generated by Django 5.2 on 2025-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(max_length=15),
        ),
    ]
