# Generated by Django 5.2 on 2025-04-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0003_patient_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="password",
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
