# Generated by Django 5.2 on 2025-04-30 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0005_appointment_is_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("C", "Confirmed"),
                    ("CA", "Cancelled"),
                    ("CO", "Completed"),
                ],
                default="P",
                max_length=4,
            ),
        ),
    ]
