# Generated by Django 5.2 on 2025-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0007_alter_doctor_email_alter_patient_email_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
